const bls = require('./bls2.js')

bls.init(5).then(() => {
  const sec = new bls.SecretKey()
console.log('SSS')
//  sec.setByCSPRNG()
  console.log(`stack=${bls.mod.getStackAddress(32)}`)
  sec.setInt(1)
  console.log(`sec=${sec.serializeToHexStr()}`)
  const sec2 = new bls.SecretKey()
  sec2.setInt(123)
  console.log(`sec2=${sec2.serializeToHexStr()}`)
  sec2.add(sec)
  console.log(`sec2=${sec2.serializeToHexStr()}`)
  const pub = sec.getPublicKey()
  const pub2 = sec.getPublicKey()
  console.log(`pub=${pub.serializeToHexStr()}`)
  console.log(`pub2=${pub2.serializeToHexStr()}`)
  pub2.add(pub)
  console.log(`pub2=${pub2.serializeToHexStr()}`)
  pub2.add(pub)
  console.log(`pub2=${pub2.serializeToHexStr()}`)
  const m = "abc"
  const sig = sec.sign(m)
  console.log(`sig=${sig.serializeToHexStr()}`)
  console.log(`verify=${pub.verify(sig, m)}`)
  console.log(`verify=${pub.verify(sig, "abd")}`)
})

